// client/src/App.vue
<script setup lang="ts">
import PageEditor from "./components/PageEditor.vue";
import PageList from "./components/PageList.vue";
import { useNotesStore } from "./stores/notes";

const store = useNotesStore();
</script>

<template>
	<div class="min-h-screen bg-zinc-9 text-neutral-1 flex flex-col-reverse p-4 md:(flex-row p-8)">
		<!-- left section -->
		<div class="grow flex flex-col">
			<PageEditor></PageEditor>
		</div>
		<!-- left section end -->

		<!-- right section -->
		<div>
			<PageList></PageList>

			<!-- icons -->
			<div></div>
		</div>
		<!-- right section end -->
	</div>
</template>

// client/src/App.tsx
import type { Component } from "solid-js";
import { Explorer } from "./components/Explorer";
import { Note } from "./components/Note";
import { Status } from "./components/Status";

const App: Component = () => {
	return (
		<div class="flex h-screen flex-row gap-2 bg-zinc-800 p-2 text-zinc-100 md:p-8">
			<div class="flex grow flex-col">
				<main class="flex grow flex-row gap-4">
					<Note></Note>
					<Explorer></Explorer>
				</main>

				<Status></Status>
			</div>
		</div>
	);
};

export default App;
